# Generated by Django 3.0.6 on 2020-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_DATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(choices=[('1', 'Andhra_Pradesh'), ('2', 'Arunachar_Pradesh'), ('3', 'Assam'), ('4', 'Bihar'), ('5', 'Chattisgarh'), ('6', 'Goa'), ('7', 'Gujrat'), ('8', 'Haryana'), ('9', 'Himachar_Pradesh'), ('10', 'Jharkhand'), ('11', 'Karnataka'), ('12', 'Kerala'), ('13', 'Madhya_Pradesh'), ('14', 'Maharashtra'), ('15', 'Manipur'), ('16', 'Meghalaya'), ('17', 'Mizoram'), ('18', 'Nagaland'), ('19', 'Odisha'), ('20', 'Punjab'), ('21', 'Rajasthan'), ('22', 'Sikkim'), ('23', 'Tamil_Nadu'), ('24', 'Telangana'), ('25', 'Tripura'), ('26', 'Uttarakhand'), ('27', 'Uttar_Pradesh'), ('28', 'West_Bengal')], max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('BloodBank_Name', models.CharField(max_length=100)),
                ('Last_Updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(default='')),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30)),
                ('query', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Donor_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_bloodgroup', models.CharField(max_length=10)),
                ('donor_address', models.CharField(max_length=500)),
                ('donor_state', models.CharField(max_length=50)),
                ('donor_district', models.CharField(max_length=50)),
                ('donor_city', models.CharField(max_length=50)),
                ('donor_pincode', models.IntegerField(default=0)),
                ('donor_phone_number', models.IntegerField(default=0)),
                ('donor_email_id', models.CharField(max_length=50)),
                ('donor_profile_pic', models.ImageField(upload_to='profiles')),
            ],
        ),
    ]
