# Generated by Django 3.0.6 on 2020-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_data',
            name='AB_Negative_Blood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blood_data',
            name='AB_Positive_Blood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blood_data',
            name='A_Negative_Blood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blood_data',
            name='A_Positive_Blood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blood_data',
            name='B_Negative_Blood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blood_data',
            name='B_Positive_Blood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blood_data',
            name='O_Negative_Blood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blood_data',
            name='O_Positive_Blood',
            field=models.IntegerField(default=0),
        ),
    ]
