# Generated by Django 3.0.6 on 2020-05-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200526_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_data',
            name='State',
            field=models.CharField(choices=[('Andhra_Pradesh', 'Andhra_Pradesh'), ('Arunachar_Pradesh', 'Arunachar_Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachar_Pradesh', 'Himachar_Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya_Pradesh', 'Madhya_Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil_Nadu', 'Tamil_Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Uttar_Pradesh', 'Uttar_Pradesh'), ('West_Bengal', 'West_Bengal')], max_length=20),
        ),
    ]
